# Generated by Django 4.1.4 on 2022-12-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending_status',
            field=models.IntegerField(choices=[(1, 'Success'), (0, 'Failure'), (-1, 'Pending'), (-2, 'Canceled')], default=0),
        ),
    ]
