# Generated by Django 4.1.4 on 2022-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__message', '0002_alter_message_sending_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='message',
            name='sending_status',
            field=models.IntegerField(choices=[(1, 'Success'), (0, 'Pending'), (-1, 'Failure'), (-2, 'Canceled')], default=0),
        ),
    ]
