# Generated by Django 4.1.4 on 2022-12-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__message', '0003_alter_message_options_alter_message_sending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending_status',
            field=models.IntegerField(choices=[(1, 'Success'), (0, 'Pending'), (-1, 'Failure')], default=0),
        ),
    ]
