# Generated by Django 4.1.4 on 2022-12-08 15:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('mailing__client', '0002_alter_client_mobile_operator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
