# Generated by Django 4.1.4 on 2022-12-08 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__client', '0004_alter_client_mobile_operator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7XXXXXXXXXX' where X: 0-9.", regex='^[7]\\d{10,10}$')]),
        ),
    ]
