# Generated by Django 4.1.4 on 2022-12-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__client', '0005_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
    ]
