# Generated by Django 4.1.4 on 2022-12-08 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__mailing', '0003_alter_mailing_end_date_alter_mailing_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 15, 34, 22, 760885, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='properties_filter',
            field=models.JSONField(blank=True, default={'filters': [{'operator_code': None}, {'tag': None}]}, null=True),
        ),
    ]
