# Generated by Django 4.1.4 on 2022-12-08 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__mailing', '0005_alter_mailing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 15, 37, 54, 850643, tzinfo=datetime.timezone.utc)),
        ),
    ]
