# Generated by Django 4.1.4 on 2022-12-09 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__mailing', '0011_alter_mailing_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 7, 18, 23, 825965, tzinfo=datetime.timezone.utc)),
        ),
    ]
