# Generated by Django 4.1.4 on 2022-12-09 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing__mailing', '0012_alter_mailing_options_alter_mailing_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 7, 54, 12, 336285, tzinfo=datetime.timezone.utc)),
        ),
    ]
